export const skillBase = [
	'Projektowanie graficzne',
	'UI / User Interface',
	'UX / User Experience',
	'UX research',
	'UX writing',
	'Tworzenie logo',
	'Responsywne projektowanie',
	'Tworzenie stron internetowych',
	'Aplikacja mobilna',
	'Aplikacja webowa',
	'Photoshop',
	'Figma',
	'Adobe XD',
];
